//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bExcellent.Service.DataAccess.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.1.84;Initial Catalog=Bexcellent_Public_DImportTest;User ID=sa" +
            ";Password=sa@123")]
        public string Bexcellent_NewConnectionString1 {
            get {
                return ((string)(this["Bexcellent_NewConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.;Initial Catalog=Bexcellent_Public_DImportTest;User ID=sa;Password=s" +
            "a@123")]
        public string Bexcellent_NewConnectionString {
            get {
                return ((string)(this["Bexcellent_NewConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.;Initial Catalog=Bexcellent_New;User ID=sa")]
        public string Bexcellent_NewConnectionString2 {
            get {
                return ((string)(this["Bexcellent_NewConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.;Initial Catalog=Bexcellent_New;User ID=sa;Password=sa@123")]
        public string Bexcellent_NewConnectionString3 {
            get {
                return ((string)(this["Bexcellent_NewConnectionString3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.1.84;Initial Catalog=Bexcellent_New;User ID=sa;Password=sa@12" +
            "3")]
        public string Bexcellent_NewConnectionString4 {
            get {
                return ((string)(this["Bexcellent_NewConnectionString4"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.1.98;Initial Catalog=Bexcellent_New;User ID=sa;Password=sa@12" +
            "3")]
        public string Bexcellent_NewConnectionString5 {
            get {
                return ((string)(this["Bexcellent_NewConnectionString5"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=LAPTOP-EO7LTA8F\\SQLEXPRESS;Initial Catalog=Kessaku;User ID=sa;Passwor" +
            "d=sa@123!")]
        public string KessakuConnectionString {
            get {
                return ((string)(this["KessakuConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=LAPTOP-EO7LTA8F\\SQLEXPRESS;Initial Catalog=Kessaku_Demo;User ID=sa;Pa" +
            "ssword=sa@123!")]
        public string Kessaku_DemoConnectionString {
            get {
                return ((string)(this["Kessaku_DemoConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=LAPTOP-EO7LTA8F\\SQLEXPRESS;Initial Catalog=PSE_Live;User ID=sa;Passwo" +
            "rd=sa@123!")]
        public string PSE_LiveConnectionString {
            get {
                return ((string)(this["PSE_LiveConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=LAPTOP-EO7LTA8F\\SQLEXPRESS;Initial Catalog=Kessaku_Live;User ID=sa;Pa" +
            "ssword=sa@123!")]
        public string Kessaku_LiveConnectionString {
            get {
                return ((string)(this["Kessaku_LiveConnectionString"]));
            }
        }
    }
}
