//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bExcellent.mvc.SignUpWCF {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SignupRequest", Namespace="http://schemas.datacontract.org/2004/07/bExcellent.Service.Util.Request")]
    [System.SerializableAttribute()]
    public partial class SignupRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bExcellent.mvc.SignUpWCF.UserPOEMapping[] MembersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ModeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bExcellent.mvc.SignUpWCF.Network NetwrokField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bExcellent.mvc.SignUpWCF.Payment PaymentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bExcellent.mvc.SignUpWCF.POE[] PoesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bExcellent.mvc.SignUpWCF.User UserField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bExcellent.mvc.SignUpWCF.UserPOEMapping[] Members {
            get {
                return this.MembersField;
            }
            set {
                if ((object.ReferenceEquals(this.MembersField, value) != true)) {
                    this.MembersField = value;
                    this.RaisePropertyChanged("Members");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Mode {
            get {
                return this.ModeField;
            }
            set {
                if ((this.ModeField.Equals(value) != true)) {
                    this.ModeField = value;
                    this.RaisePropertyChanged("Mode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bExcellent.mvc.SignUpWCF.Network Netwrok {
            get {
                return this.NetwrokField;
            }
            set {
                if ((object.ReferenceEquals(this.NetwrokField, value) != true)) {
                    this.NetwrokField = value;
                    this.RaisePropertyChanged("Netwrok");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bExcellent.mvc.SignUpWCF.Payment Payment {
            get {
                return this.PaymentField;
            }
            set {
                if ((object.ReferenceEquals(this.PaymentField, value) != true)) {
                    this.PaymentField = value;
                    this.RaisePropertyChanged("Payment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bExcellent.mvc.SignUpWCF.POE[] Poes {
            get {
                return this.PoesField;
            }
            set {
                if ((object.ReferenceEquals(this.PoesField, value) != true)) {
                    this.PoesField = value;
                    this.RaisePropertyChanged("Poes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bExcellent.mvc.SignUpWCF.User User {
            get {
                return this.UserField;
            }
            set {
                if ((object.ReferenceEquals(this.UserField, value) != true)) {
                    this.UserField = value;
                    this.RaisePropertyChanged("User");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Network", Namespace="http://schemas.datacontract.org/2004/07/bExcellent.Service.Util.Domain")]
    [System.SerializableAttribute()]
    public partial class Network : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreatedOnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NetworkNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PlanField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SubscriptionidField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreatedOn {
            get {
                return this.CreatedOnField;
            }
            set {
                if ((this.CreatedOnField.Equals(value) != true)) {
                    this.CreatedOnField = value;
                    this.RaisePropertyChanged("CreatedOn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmailId {
            get {
                return this.EmailIdField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailIdField, value) != true)) {
                    this.EmailIdField = value;
                    this.RaisePropertyChanged("EmailId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NetworkName {
            get {
                return this.NetworkNameField;
            }
            set {
                if ((object.ReferenceEquals(this.NetworkNameField, value) != true)) {
                    this.NetworkNameField = value;
                    this.RaisePropertyChanged("NetworkName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Plan {
            get {
                return this.PlanField;
            }
            set {
                if ((this.PlanField.Equals(value) != true)) {
                    this.PlanField = value;
                    this.RaisePropertyChanged("Plan");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Subscriptionid {
            get {
                return this.SubscriptionidField;
            }
            set {
                if ((this.SubscriptionidField.Equals(value) != true)) {
                    this.SubscriptionidField = value;
                    this.RaisePropertyChanged("Subscriptionid");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Payment", Namespace="http://schemas.datacontract.org/2004/07/bExcellent.Service.Util.Domain")]
    [System.SerializableAttribute()]
    public partial class Payment : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Address1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Address2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal AmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CVVField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreditCardField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResponseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResponseIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ZipField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address1 {
            get {
                return this.Address1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Address1Field, value) != true)) {
                    this.Address1Field = value;
                    this.RaisePropertyChanged("Address1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address2 {
            get {
                return this.Address2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Address2Field, value) != true)) {
                    this.Address2Field = value;
                    this.RaisePropertyChanged("Address2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Amount {
            get {
                return this.AmountField;
            }
            set {
                if ((this.AmountField.Equals(value) != true)) {
                    this.AmountField = value;
                    this.RaisePropertyChanged("Amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CVV {
            get {
                return this.CVVField;
            }
            set {
                if ((object.ReferenceEquals(this.CVVField, value) != true)) {
                    this.CVVField = value;
                    this.RaisePropertyChanged("CVV");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Country {
            get {
                return this.CountryField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryField, value) != true)) {
                    this.CountryField = value;
                    this.RaisePropertyChanged("Country");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreditCard {
            get {
                return this.CreditCardField;
            }
            set {
                if ((object.ReferenceEquals(this.CreditCardField, value) != true)) {
                    this.CreditCardField = value;
                    this.RaisePropertyChanged("CreditCard");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Response {
            get {
                return this.ResponseField;
            }
            set {
                if ((object.ReferenceEquals(this.ResponseField, value) != true)) {
                    this.ResponseField = value;
                    this.RaisePropertyChanged("Response");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResponseId {
            get {
                return this.ResponseIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ResponseIdField, value) != true)) {
                    this.ResponseIdField = value;
                    this.RaisePropertyChanged("ResponseId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string State {
            get {
                return this.StateField;
            }
            set {
                if ((object.ReferenceEquals(this.StateField, value) != true)) {
                    this.StateField = value;
                    this.RaisePropertyChanged("State");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Zip {
            get {
                return this.ZipField;
            }
            set {
                if ((object.ReferenceEquals(this.ZipField, value) != true)) {
                    this.ZipField = value;
                    this.RaisePropertyChanged("Zip");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="")]
    [System.SerializableAttribute()]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bExcellent.mvc.SignUpWCF.Zone AreaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompanyNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompanySizeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bExcellent.mvc.SignUpWCF.Country CountryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DesignationIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsActiveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> IsAgreedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string JobTitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> LastLoginField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] PhotoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StratPageModeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> SubscriptionidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string YammerTokenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string userNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bExcellent.mvc.SignUpWCF.Zone Area {
            get {
                return this.AreaField;
            }
            set {
                if ((object.ReferenceEquals(this.AreaField, value) != true)) {
                    this.AreaField = value;
                    this.RaisePropertyChanged("Area");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CompanyName {
            get {
                return this.CompanyNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyNameField, value) != true)) {
                    this.CompanyNameField = value;
                    this.RaisePropertyChanged("CompanyName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CompanySize {
            get {
                return this.CompanySizeField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanySizeField, value) != true)) {
                    this.CompanySizeField = value;
                    this.RaisePropertyChanged("CompanySize");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bExcellent.mvc.SignUpWCF.Country Country {
            get {
                return this.CountryField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryField, value) != true)) {
                    this.CountryField = value;
                    this.RaisePropertyChanged("Country");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DesignationId {
            get {
                return this.DesignationIdField;
            }
            set {
                if ((this.DesignationIdField.Equals(value) != true)) {
                    this.DesignationIdField = value;
                    this.RaisePropertyChanged("DesignationId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmailAddress {
            get {
                return this.EmailAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailAddressField, value) != true)) {
                    this.EmailAddressField = value;
                    this.RaisePropertyChanged("EmailAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsActive {
            get {
                return this.IsActiveField;
            }
            set {
                if ((this.IsActiveField.Equals(value) != true)) {
                    this.IsActiveField = value;
                    this.RaisePropertyChanged("IsActive");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> IsAgreed {
            get {
                return this.IsAgreedField;
            }
            set {
                if ((this.IsAgreedField.Equals(value) != true)) {
                    this.IsAgreedField = value;
                    this.RaisePropertyChanged("IsAgreed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string JobTitle {
            get {
                return this.JobTitleField;
            }
            set {
                if ((object.ReferenceEquals(this.JobTitleField, value) != true)) {
                    this.JobTitleField = value;
                    this.RaisePropertyChanged("JobTitle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> LastLogin {
            get {
                return this.LastLoginField;
            }
            set {
                if ((this.LastLoginField.Equals(value) != true)) {
                    this.LastLoginField = value;
                    this.RaisePropertyChanged("LastLogin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Photo {
            get {
                return this.PhotoField;
            }
            set {
                if ((object.ReferenceEquals(this.PhotoField, value) != true)) {
                    this.PhotoField = value;
                    this.RaisePropertyChanged("Photo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StratPageMode {
            get {
                return this.StratPageModeField;
            }
            set {
                if ((this.StratPageModeField.Equals(value) != true)) {
                    this.StratPageModeField = value;
                    this.RaisePropertyChanged("StratPageMode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Subscriptionid {
            get {
                return this.SubscriptionidField;
            }
            set {
                if ((this.SubscriptionidField.Equals(value) != true)) {
                    this.SubscriptionidField = value;
                    this.RaisePropertyChanged("Subscriptionid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string YammerToken {
            get {
                return this.YammerTokenField;
            }
            set {
                if ((object.ReferenceEquals(this.YammerTokenField, value) != true)) {
                    this.YammerTokenField = value;
                    this.RaisePropertyChanged("YammerToken");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string userName {
            get {
                return this.userNameField;
            }
            set {
                if ((object.ReferenceEquals(this.userNameField, value) != true)) {
                    this.userNameField = value;
                    this.RaisePropertyChanged("userName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserPOEMapping", Namespace="http://schemas.datacontract.org/2004/07/bExcellent.Service.Util.Domain")]
    [System.SerializableAttribute()]
    public partial class UserPOEMapping : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AreaIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ChildMappingIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bExcellent.mvc.SignUpWCF.Designation DesignationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> DurationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bExcellent.mvc.SignUpWCF.Feedback FeedbackDetailsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string JobTitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NooffbsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bExcellent.mvc.SignUpWCF.POE POEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int POEIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ParentMappingIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PeerChildMappingIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PeerParentMappingIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float PoeAmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RegionIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RoleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SecondaryUserPOEMappingIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubscribtionDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bExcellent.mvc.SignUpWCF.User UserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float UserAmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserPOEMappingIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double WcsiScoreDiffField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AreaId {
            get {
                return this.AreaIdField;
            }
            set {
                if ((this.AreaIdField.Equals(value) != true)) {
                    this.AreaIdField = value;
                    this.RaisePropertyChanged("AreaId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ChildMappingId {
            get {
                return this.ChildMappingIdField;
            }
            set {
                if ((this.ChildMappingIdField.Equals(value) != true)) {
                    this.ChildMappingIdField = value;
                    this.RaisePropertyChanged("ChildMappingId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bExcellent.mvc.SignUpWCF.Designation Designation {
            get {
                return this.DesignationField;
            }
            set {
                if ((object.ReferenceEquals(this.DesignationField, value) != true)) {
                    this.DesignationField = value;
                    this.RaisePropertyChanged("Designation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> Duration {
            get {
                return this.DurationField;
            }
            set {
                if ((this.DurationField.Equals(value) != true)) {
                    this.DurationField = value;
                    this.RaisePropertyChanged("Duration");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bExcellent.mvc.SignUpWCF.Feedback FeedbackDetails {
            get {
                return this.FeedbackDetailsField;
            }
            set {
                if ((object.ReferenceEquals(this.FeedbackDetailsField, value) != true)) {
                    this.FeedbackDetailsField = value;
                    this.RaisePropertyChanged("FeedbackDetails");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string JobTitle {
            get {
                return this.JobTitleField;
            }
            set {
                if ((object.ReferenceEquals(this.JobTitleField, value) != true)) {
                    this.JobTitleField = value;
                    this.RaisePropertyChanged("JobTitle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Nooffbs {
            get {
                return this.NooffbsField;
            }
            set {
                if ((this.NooffbsField.Equals(value) != true)) {
                    this.NooffbsField = value;
                    this.RaisePropertyChanged("Nooffbs");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bExcellent.mvc.SignUpWCF.POE POE {
            get {
                return this.POEField;
            }
            set {
                if ((object.ReferenceEquals(this.POEField, value) != true)) {
                    this.POEField = value;
                    this.RaisePropertyChanged("POE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int POEId {
            get {
                return this.POEIdField;
            }
            set {
                if ((this.POEIdField.Equals(value) != true)) {
                    this.POEIdField = value;
                    this.RaisePropertyChanged("POEId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ParentMappingId {
            get {
                return this.ParentMappingIdField;
            }
            set {
                if ((this.ParentMappingIdField.Equals(value) != true)) {
                    this.ParentMappingIdField = value;
                    this.RaisePropertyChanged("ParentMappingId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PeerChildMappingId {
            get {
                return this.PeerChildMappingIdField;
            }
            set {
                if ((this.PeerChildMappingIdField.Equals(value) != true)) {
                    this.PeerChildMappingIdField = value;
                    this.RaisePropertyChanged("PeerChildMappingId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PeerParentMappingId {
            get {
                return this.PeerParentMappingIdField;
            }
            set {
                if ((this.PeerParentMappingIdField.Equals(value) != true)) {
                    this.PeerParentMappingIdField = value;
                    this.RaisePropertyChanged("PeerParentMappingId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float PoeAmount {
            get {
                return this.PoeAmountField;
            }
            set {
                if ((this.PoeAmountField.Equals(value) != true)) {
                    this.PoeAmountField = value;
                    this.RaisePropertyChanged("PoeAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RegionId {
            get {
                return this.RegionIdField;
            }
            set {
                if ((this.RegionIdField.Equals(value) != true)) {
                    this.RegionIdField = value;
                    this.RaisePropertyChanged("RegionId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Role {
            get {
                return this.RoleField;
            }
            set {
                if ((this.RoleField.Equals(value) != true)) {
                    this.RoleField = value;
                    this.RaisePropertyChanged("Role");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SecondaryUserPOEMappingId {
            get {
                return this.SecondaryUserPOEMappingIdField;
            }
            set {
                if ((this.SecondaryUserPOEMappingIdField.Equals(value) != true)) {
                    this.SecondaryUserPOEMappingIdField = value;
                    this.RaisePropertyChanged("SecondaryUserPOEMappingId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SubscribtionDate {
            get {
                return this.SubscribtionDateField;
            }
            set {
                if ((object.ReferenceEquals(this.SubscribtionDateField, value) != true)) {
                    this.SubscribtionDateField = value;
                    this.RaisePropertyChanged("SubscribtionDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bExcellent.mvc.SignUpWCF.User User {
            get {
                return this.UserField;
            }
            set {
                if ((object.ReferenceEquals(this.UserField, value) != true)) {
                    this.UserField = value;
                    this.RaisePropertyChanged("User");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float UserAmount {
            get {
                return this.UserAmountField;
            }
            set {
                if ((this.UserAmountField.Equals(value) != true)) {
                    this.UserAmountField = value;
                    this.RaisePropertyChanged("UserAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserPOEMappingId {
            get {
                return this.UserPOEMappingIdField;
            }
            set {
                if ((this.UserPOEMappingIdField.Equals(value) != true)) {
                    this.UserPOEMappingIdField = value;
                    this.RaisePropertyChanged("UserPOEMappingId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double WcsiScoreDiff {
            get {
                return this.WcsiScoreDiffField;
            }
            set {
                if ((this.WcsiScoreDiffField.Equals(value) != true)) {
                    this.WcsiScoreDiffField = value;
                    this.RaisePropertyChanged("WcsiScoreDiff");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="POE", Namespace="http://schemas.datacontract.org/2004/07/bExcellent.Service.Util.Domain")]
    [System.SerializableAttribute()]
    public partial class POE : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IntroContentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bExcellent.mvc.SignUpWCF.Module[] ModulesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int POEIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float PoeAmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PoeFlagField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubscribedPoeDateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IntroContent {
            get {
                return this.IntroContentField;
            }
            set {
                if ((object.ReferenceEquals(this.IntroContentField, value) != true)) {
                    this.IntroContentField = value;
                    this.RaisePropertyChanged("IntroContent");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bExcellent.mvc.SignUpWCF.Module[] Modules {
            get {
                return this.ModulesField;
            }
            set {
                if ((object.ReferenceEquals(this.ModulesField, value) != true)) {
                    this.ModulesField = value;
                    this.RaisePropertyChanged("Modules");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int POEId {
            get {
                return this.POEIdField;
            }
            set {
                if ((this.POEIdField.Equals(value) != true)) {
                    this.POEIdField = value;
                    this.RaisePropertyChanged("POEId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float PoeAmount {
            get {
                return this.PoeAmountField;
            }
            set {
                if ((this.PoeAmountField.Equals(value) != true)) {
                    this.PoeAmountField = value;
                    this.RaisePropertyChanged("PoeAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PoeFlag {
            get {
                return this.PoeFlagField;
            }
            set {
                if ((this.PoeFlagField.Equals(value) != true)) {
                    this.PoeFlagField = value;
                    this.RaisePropertyChanged("PoeFlag");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SubscribedPoeDate {
            get {
                return this.SubscribedPoeDateField;
            }
            set {
                if ((object.ReferenceEquals(this.SubscribedPoeDateField, value) != true)) {
                    this.SubscribedPoeDateField = value;
                    this.RaisePropertyChanged("SubscribedPoeDate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Designation", Namespace="http://schemas.datacontract.org/2004/07/bExcellent.Service.Util.Domain")]
    [System.SerializableAttribute()]
    public partial class Designation : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DesignationIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LevelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DesignationId {
            get {
                return this.DesignationIdField;
            }
            set {
                if ((this.DesignationIdField.Equals(value) != true)) {
                    this.DesignationIdField = value;
                    this.RaisePropertyChanged("DesignationId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Level {
            get {
                return this.LevelField;
            }
            set {
                if ((this.LevelField.Equals(value) != true)) {
                    this.LevelField = value;
                    this.RaisePropertyChanged("Level");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Feedback", Namespace="http://schemas.datacontract.org/2004/07/bExcellent.Service.Util.Domain")]
    [System.SerializableAttribute()]
    public partial class Feedback : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreatedOnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreatedOnDtmField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FeedbackIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bExcellent.mvc.SignUpWCF.FeedbackStatus FeedbackStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bExcellent.mvc.SignUpWCF.FeedbackType FeedbackTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GroupNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bExcellent.mvc.SignUpWCF.UserPOEMapping RequestedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RequestedByIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bExcellent.mvc.SignUpWCF.UserPOEMapping RequestedForField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RequestedForIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bExcellent.mvc.SignUpWCF.UserPOEMapping RequestedFromField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RequestedFromIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UpdatedOnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime UpdatedOnDtmField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreatedOn {
            get {
                return this.CreatedOnField;
            }
            set {
                if ((object.ReferenceEquals(this.CreatedOnField, value) != true)) {
                    this.CreatedOnField = value;
                    this.RaisePropertyChanged("CreatedOn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreatedOnDtm {
            get {
                return this.CreatedOnDtmField;
            }
            set {
                if ((this.CreatedOnDtmField.Equals(value) != true)) {
                    this.CreatedOnDtmField = value;
                    this.RaisePropertyChanged("CreatedOnDtm");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FeedbackId {
            get {
                return this.FeedbackIdField;
            }
            set {
                if ((this.FeedbackIdField.Equals(value) != true)) {
                    this.FeedbackIdField = value;
                    this.RaisePropertyChanged("FeedbackId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bExcellent.mvc.SignUpWCF.FeedbackStatus FeedbackStatus {
            get {
                return this.FeedbackStatusField;
            }
            set {
                if ((this.FeedbackStatusField.Equals(value) != true)) {
                    this.FeedbackStatusField = value;
                    this.RaisePropertyChanged("FeedbackStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bExcellent.mvc.SignUpWCF.FeedbackType FeedbackType {
            get {
                return this.FeedbackTypeField;
            }
            set {
                if ((this.FeedbackTypeField.Equals(value) != true)) {
                    this.FeedbackTypeField = value;
                    this.RaisePropertyChanged("FeedbackType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GroupName {
            get {
                return this.GroupNameField;
            }
            set {
                if ((object.ReferenceEquals(this.GroupNameField, value) != true)) {
                    this.GroupNameField = value;
                    this.RaisePropertyChanged("GroupName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bExcellent.mvc.SignUpWCF.UserPOEMapping RequestedBy {
            get {
                return this.RequestedByField;
            }
            set {
                if ((object.ReferenceEquals(this.RequestedByField, value) != true)) {
                    this.RequestedByField = value;
                    this.RaisePropertyChanged("RequestedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RequestedById {
            get {
                return this.RequestedByIdField;
            }
            set {
                if ((this.RequestedByIdField.Equals(value) != true)) {
                    this.RequestedByIdField = value;
                    this.RaisePropertyChanged("RequestedById");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bExcellent.mvc.SignUpWCF.UserPOEMapping RequestedFor {
            get {
                return this.RequestedForField;
            }
            set {
                if ((object.ReferenceEquals(this.RequestedForField, value) != true)) {
                    this.RequestedForField = value;
                    this.RaisePropertyChanged("RequestedFor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RequestedForId {
            get {
                return this.RequestedForIdField;
            }
            set {
                if ((this.RequestedForIdField.Equals(value) != true)) {
                    this.RequestedForIdField = value;
                    this.RaisePropertyChanged("RequestedForId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bExcellent.mvc.SignUpWCF.UserPOEMapping RequestedFrom {
            get {
                return this.RequestedFromField;
            }
            set {
                if ((object.ReferenceEquals(this.RequestedFromField, value) != true)) {
                    this.RequestedFromField = value;
                    this.RaisePropertyChanged("RequestedFrom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RequestedFromId {
            get {
                return this.RequestedFromIdField;
            }
            set {
                if ((this.RequestedFromIdField.Equals(value) != true)) {
                    this.RequestedFromIdField = value;
                    this.RaisePropertyChanged("RequestedFromId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UpdatedOn {
            get {
                return this.UpdatedOnField;
            }
            set {
                if ((object.ReferenceEquals(this.UpdatedOnField, value) != true)) {
                    this.UpdatedOnField = value;
                    this.RaisePropertyChanged("UpdatedOn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime UpdatedOnDtm {
            get {
                return this.UpdatedOnDtmField;
            }
            set {
                if ((this.UpdatedOnDtmField.Equals(value) != true)) {
                    this.UpdatedOnDtmField = value;
                    this.RaisePropertyChanged("UpdatedOnDtm");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FeedbackStatus", Namespace="http://schemas.datacontract.org/2004/07/bExcellent.Service.Util.Enumeration")]
    public enum FeedbackStatus : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotStarted = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InProgress = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Complete = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FeedbackType", Namespace="http://schemas.datacontract.org/2004/07/bExcellent.Service.Util.Enumeration")]
    public enum FeedbackType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Self = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Manager = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Module", Namespace="http://schemas.datacontract.org/2004/07/bExcellent.Service.Util.Domain")]
    [System.SerializableAttribute()]
    public partial class Module : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ActiveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bExcellent.mvc.SignUpWCF.CourseDetail[] CourseDetailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IndexTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KeyActionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KeyAction1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KeyAction2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KeyAction3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KeyAction4Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KeyAction5Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int KeyActionSlideCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ModuleIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModuleIntroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModuleIntro1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModuleIntro2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModuleIntro3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModuleIntro4Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModuleIntro5Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ModuleIntroSlideCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModuleNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ModuleOrderNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int POEIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bExcellent.mvc.SignUpWCF.Question[] QuestionsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Active {
            get {
                return this.ActiveField;
            }
            set {
                if ((this.ActiveField.Equals(value) != true)) {
                    this.ActiveField = value;
                    this.RaisePropertyChanged("Active");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bExcellent.mvc.SignUpWCF.CourseDetail[] CourseDetail {
            get {
                return this.CourseDetailField;
            }
            set {
                if ((object.ReferenceEquals(this.CourseDetailField, value) != true)) {
                    this.CourseDetailField = value;
                    this.RaisePropertyChanged("CourseDetail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IndexType {
            get {
                return this.IndexTypeField;
            }
            set {
                if ((this.IndexTypeField.Equals(value) != true)) {
                    this.IndexTypeField = value;
                    this.RaisePropertyChanged("IndexType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string KeyAction {
            get {
                return this.KeyActionField;
            }
            set {
                if ((object.ReferenceEquals(this.KeyActionField, value) != true)) {
                    this.KeyActionField = value;
                    this.RaisePropertyChanged("KeyAction");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string KeyAction1 {
            get {
                return this.KeyAction1Field;
            }
            set {
                if ((object.ReferenceEquals(this.KeyAction1Field, value) != true)) {
                    this.KeyAction1Field = value;
                    this.RaisePropertyChanged("KeyAction1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string KeyAction2 {
            get {
                return this.KeyAction2Field;
            }
            set {
                if ((object.ReferenceEquals(this.KeyAction2Field, value) != true)) {
                    this.KeyAction2Field = value;
                    this.RaisePropertyChanged("KeyAction2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string KeyAction3 {
            get {
                return this.KeyAction3Field;
            }
            set {
                if ((object.ReferenceEquals(this.KeyAction3Field, value) != true)) {
                    this.KeyAction3Field = value;
                    this.RaisePropertyChanged("KeyAction3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string KeyAction4 {
            get {
                return this.KeyAction4Field;
            }
            set {
                if ((object.ReferenceEquals(this.KeyAction4Field, value) != true)) {
                    this.KeyAction4Field = value;
                    this.RaisePropertyChanged("KeyAction4");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string KeyAction5 {
            get {
                return this.KeyAction5Field;
            }
            set {
                if ((object.ReferenceEquals(this.KeyAction5Field, value) != true)) {
                    this.KeyAction5Field = value;
                    this.RaisePropertyChanged("KeyAction5");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int KeyActionSlideCount {
            get {
                return this.KeyActionSlideCountField;
            }
            set {
                if ((this.KeyActionSlideCountField.Equals(value) != true)) {
                    this.KeyActionSlideCountField = value;
                    this.RaisePropertyChanged("KeyActionSlideCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ModuleId {
            get {
                return this.ModuleIdField;
            }
            set {
                if ((this.ModuleIdField.Equals(value) != true)) {
                    this.ModuleIdField = value;
                    this.RaisePropertyChanged("ModuleId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ModuleIntro {
            get {
                return this.ModuleIntroField;
            }
            set {
                if ((object.ReferenceEquals(this.ModuleIntroField, value) != true)) {
                    this.ModuleIntroField = value;
                    this.RaisePropertyChanged("ModuleIntro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ModuleIntro1 {
            get {
                return this.ModuleIntro1Field;
            }
            set {
                if ((object.ReferenceEquals(this.ModuleIntro1Field, value) != true)) {
                    this.ModuleIntro1Field = value;
                    this.RaisePropertyChanged("ModuleIntro1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ModuleIntro2 {
            get {
                return this.ModuleIntro2Field;
            }
            set {
                if ((object.ReferenceEquals(this.ModuleIntro2Field, value) != true)) {
                    this.ModuleIntro2Field = value;
                    this.RaisePropertyChanged("ModuleIntro2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ModuleIntro3 {
            get {
                return this.ModuleIntro3Field;
            }
            set {
                if ((object.ReferenceEquals(this.ModuleIntro3Field, value) != true)) {
                    this.ModuleIntro3Field = value;
                    this.RaisePropertyChanged("ModuleIntro3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ModuleIntro4 {
            get {
                return this.ModuleIntro4Field;
            }
            set {
                if ((object.ReferenceEquals(this.ModuleIntro4Field, value) != true)) {
                    this.ModuleIntro4Field = value;
                    this.RaisePropertyChanged("ModuleIntro4");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ModuleIntro5 {
            get {
                return this.ModuleIntro5Field;
            }
            set {
                if ((object.ReferenceEquals(this.ModuleIntro5Field, value) != true)) {
                    this.ModuleIntro5Field = value;
                    this.RaisePropertyChanged("ModuleIntro5");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ModuleIntroSlideCount {
            get {
                return this.ModuleIntroSlideCountField;
            }
            set {
                if ((this.ModuleIntroSlideCountField.Equals(value) != true)) {
                    this.ModuleIntroSlideCountField = value;
                    this.RaisePropertyChanged("ModuleIntroSlideCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ModuleName {
            get {
                return this.ModuleNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ModuleNameField, value) != true)) {
                    this.ModuleNameField = value;
                    this.RaisePropertyChanged("ModuleName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ModuleOrderNumber {
            get {
                return this.ModuleOrderNumberField;
            }
            set {
                if ((this.ModuleOrderNumberField.Equals(value) != true)) {
                    this.ModuleOrderNumberField = value;
                    this.RaisePropertyChanged("ModuleOrderNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int POEId {
            get {
                return this.POEIdField;
            }
            set {
                if ((this.POEIdField.Equals(value) != true)) {
                    this.POEIdField = value;
                    this.RaisePropertyChanged("POEId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bExcellent.mvc.SignUpWCF.Question[] Questions {
            get {
                return this.QuestionsField;
            }
            set {
                if ((object.ReferenceEquals(this.QuestionsField, value) != true)) {
                    this.QuestionsField = value;
                    this.RaisePropertyChanged("Questions");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CourseDetail", Namespace="http://schemas.datacontract.org/2004/07/bExcellent.Service.Util.Domain")]
    [System.SerializableAttribute()]
    public partial class CourseDetail : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ContentlengthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CourseContentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CourseLinkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CourseTitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CourseidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LinkCountField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Contentlength {
            get {
                return this.ContentlengthField;
            }
            set {
                if ((this.ContentlengthField.Equals(value) != true)) {
                    this.ContentlengthField = value;
                    this.RaisePropertyChanged("Contentlength");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CourseContent {
            get {
                return this.CourseContentField;
            }
            set {
                if ((object.ReferenceEquals(this.CourseContentField, value) != true)) {
                    this.CourseContentField = value;
                    this.RaisePropertyChanged("CourseContent");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CourseLink {
            get {
                return this.CourseLinkField;
            }
            set {
                if ((object.ReferenceEquals(this.CourseLinkField, value) != true)) {
                    this.CourseLinkField = value;
                    this.RaisePropertyChanged("CourseLink");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CourseTitle {
            get {
                return this.CourseTitleField;
            }
            set {
                if ((object.ReferenceEquals(this.CourseTitleField, value) != true)) {
                    this.CourseTitleField = value;
                    this.RaisePropertyChanged("CourseTitle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Courseid {
            get {
                return this.CourseidField;
            }
            set {
                if ((this.CourseidField.Equals(value) != true)) {
                    this.CourseidField = value;
                    this.RaisePropertyChanged("Courseid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LinkCount {
            get {
                return this.LinkCountField;
            }
            set {
                if ((this.LinkCountField.Equals(value) != true)) {
                    this.LinkCountField = value;
                    this.RaisePropertyChanged("LinkCount");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Question", Namespace="http://schemas.datacontract.org/2004/07/bExcellent.Service.Util.Domain")]
    [System.SerializableAttribute()]
    public partial class Question : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> AnswerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CommentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsBarrierQuestionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int QuestionIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int QuestionOrderNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string QuetionTextField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ShortQuetionTextField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SideBarTitleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Answer {
            get {
                return this.AnswerField;
            }
            set {
                if ((this.AnswerField.Equals(value) != true)) {
                    this.AnswerField = value;
                    this.RaisePropertyChanged("Answer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Comment {
            get {
                return this.CommentField;
            }
            set {
                if ((object.ReferenceEquals(this.CommentField, value) != true)) {
                    this.CommentField = value;
                    this.RaisePropertyChanged("Comment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsBarrierQuestion {
            get {
                return this.IsBarrierQuestionField;
            }
            set {
                if ((this.IsBarrierQuestionField.Equals(value) != true)) {
                    this.IsBarrierQuestionField = value;
                    this.RaisePropertyChanged("IsBarrierQuestion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int QuestionId {
            get {
                return this.QuestionIdField;
            }
            set {
                if ((this.QuestionIdField.Equals(value) != true)) {
                    this.QuestionIdField = value;
                    this.RaisePropertyChanged("QuestionId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int QuestionOrderNumber {
            get {
                return this.QuestionOrderNumberField;
            }
            set {
                if ((this.QuestionOrderNumberField.Equals(value) != true)) {
                    this.QuestionOrderNumberField = value;
                    this.RaisePropertyChanged("QuestionOrderNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string QuetionText {
            get {
                return this.QuetionTextField;
            }
            set {
                if ((object.ReferenceEquals(this.QuetionTextField, value) != true)) {
                    this.QuetionTextField = value;
                    this.RaisePropertyChanged("QuetionText");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ShortQuetionText {
            get {
                return this.ShortQuetionTextField;
            }
            set {
                if ((object.ReferenceEquals(this.ShortQuetionTextField, value) != true)) {
                    this.ShortQuetionTextField = value;
                    this.RaisePropertyChanged("ShortQuetionText");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SideBarTitle {
            get {
                return this.SideBarTitleField;
            }
            set {
                if ((object.ReferenceEquals(this.SideBarTitleField, value) != true)) {
                    this.SideBarTitleField = value;
                    this.RaisePropertyChanged("SideBarTitle");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Zone", Namespace="http://schemas.datacontract.org/2004/07/bExcellent.Service.Util.Domain")]
    [System.SerializableAttribute()]
    public partial class Zone : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CountryIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CountryId {
            get {
                return this.CountryIdField;
            }
            set {
                if ((this.CountryIdField.Equals(value) != true)) {
                    this.CountryIdField = value;
                    this.RaisePropertyChanged("CountryId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Country", Namespace="http://schemas.datacontract.org/2004/07/bExcellent.Service.Util.Domain")]
    [System.SerializableAttribute()]
    public partial class Country : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SignUpWCF.Signup")]
    public interface Signup {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Signup/SignUp", ReplyAction="http://tempuri.org/Signup/SignUpResponse")]
        bool SignUp(bExcellent.mvc.SignUpWCF.SignupRequest sr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Signup/UpdateUserPhoto", ReplyAction="http://tempuri.org/Signup/UpdateUserPhotoResponse")]
        bool UpdateUserPhoto(bExcellent.mvc.SignUpWCF.SignupRequest sr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Signup/CheckEmailId", ReplyAction="http://tempuri.org/Signup/CheckEmailIdResponse")]
        bool CheckEmailId(string EmailId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Signup/UpdateAcessToken", ReplyAction="http://tempuri.org/Signup/UpdateAcessTokenResponse")]
        void UpdateAcessToken(string emailid, string accestoken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Signup/GetMyUsers", ReplyAction="http://tempuri.org/Signup/GetMyUsersResponse")]
        bExcellent.mvc.SignUpWCF.UserPOEMapping[] GetMyUsers(int userId, int subscriptionid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Signup/GetMyAllUsers", ReplyAction="http://tempuri.org/Signup/GetMyAllUsersResponse")]
        bExcellent.mvc.SignUpWCF.UserPOEMapping[] GetMyAllUsers(int userId, int subscriptionid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Signup/GetUserById", ReplyAction="http://tempuri.org/Signup/GetUserByIdResponse")]
        bExcellent.mvc.SignUpWCF.User GetUserById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Signup/GetNetworkById", ReplyAction="http://tempuri.org/Signup/GetNetworkByIdResponse")]
        bExcellent.mvc.SignUpWCF.Network GetNetworkById(int networkId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Signup/CheckNetwork", ReplyAction="http://tempuri.org/Signup/CheckNetworkResponse")]
        bool CheckNetwork(string networkName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Signup/GetAllPoEs", ReplyAction="http://tempuri.org/Signup/GetAllPoEsResponse")]
        bExcellent.mvc.SignUpWCF.POE[] GetAllPoEs();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Signup/GetSubscribedPoes", ReplyAction="http://tempuri.org/Signup/GetSubscribedPoesResponse")]
        bExcellent.mvc.SignUpWCF.POE[] GetSubscribedPoes(int subId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Signup/GetSubscribedPoesList", ReplyAction="http://tempuri.org/Signup/GetSubscribedPoesListResponse")]
        bExcellent.mvc.SignUpWCF.POE[] GetSubscribedPoesList(int userid, int subId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Signup/AssignPoeRecord", ReplyAction="http://tempuri.org/Signup/AssignPoeRecordResponse")]
        bool AssignPoeRecord(bExcellent.mvc.SignUpWCF.SignupRequest assignPoes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Signup/DeleteSubscribedUsers", ReplyAction="http://tempuri.org/Signup/DeleteSubscribedUsersResponse")]
        void DeleteSubscribedUsers(string emailid, int subid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Signup/DeleteSubscribedPoe", ReplyAction="http://tempuri.org/Signup/DeleteSubscribedPoeResponse")]
        void DeleteSubscribedPoe(int Poeid, int subid);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SignupChannel : bExcellent.mvc.SignUpWCF.Signup, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SignupClient : System.ServiceModel.ClientBase<bExcellent.mvc.SignUpWCF.Signup>, bExcellent.mvc.SignUpWCF.Signup {
        
        public SignupClient() {
        }
        
        public SignupClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SignupClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SignupClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SignupClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool SignUp(bExcellent.mvc.SignUpWCF.SignupRequest sr) {
            return base.Channel.SignUp(sr);
        }
        
        public bool UpdateUserPhoto(bExcellent.mvc.SignUpWCF.SignupRequest sr) {
            return base.Channel.UpdateUserPhoto(sr);
        }
        
        public bool CheckEmailId(string EmailId) {
            return base.Channel.CheckEmailId(EmailId);
        }
        
        public void UpdateAcessToken(string emailid, string accestoken) {
            base.Channel.UpdateAcessToken(emailid, accestoken);
        }
        
        public bExcellent.mvc.SignUpWCF.UserPOEMapping[] GetMyUsers(int userId, int subscriptionid) {
            return base.Channel.GetMyUsers(userId, subscriptionid);
        }
        
        public bExcellent.mvc.SignUpWCF.UserPOEMapping[] GetMyAllUsers(int userId, int subscriptionid) {
            return base.Channel.GetMyAllUsers(userId, subscriptionid);
        }
        
        public bExcellent.mvc.SignUpWCF.User GetUserById(int id) {
            return base.Channel.GetUserById(id);
        }
        
        public bExcellent.mvc.SignUpWCF.Network GetNetworkById(int networkId) {
            return base.Channel.GetNetworkById(networkId);
        }
        
        public bool CheckNetwork(string networkName) {
            return base.Channel.CheckNetwork(networkName);
        }
        
        public bExcellent.mvc.SignUpWCF.POE[] GetAllPoEs() {
            return base.Channel.GetAllPoEs();
        }
        
        public bExcellent.mvc.SignUpWCF.POE[] GetSubscribedPoes(int subId) {
            return base.Channel.GetSubscribedPoes(subId);
        }
        
        public bExcellent.mvc.SignUpWCF.POE[] GetSubscribedPoesList(int userid, int subId) {
            return base.Channel.GetSubscribedPoesList(userid, subId);
        }
        
        public bool AssignPoeRecord(bExcellent.mvc.SignUpWCF.SignupRequest assignPoes) {
            return base.Channel.AssignPoeRecord(assignPoes);
        }
        
        public void DeleteSubscribedUsers(string emailid, int subid) {
            base.Channel.DeleteSubscribedUsers(emailid, subid);
        }
        
        public void DeleteSubscribedPoe(int Poeid, int subid) {
            base.Channel.DeleteSubscribedPoe(Poeid, subid);
        }
    }
}
